site_name: Personal Knowledge Graphs
nav:
  - Home: index.md
  - Introduction:
    - About: about.md
    - Outline: intro/outline.md
    - What is a PKG?: intro/what-is-a-pkg.md
  - Integration:
    - Intro: integration/index.md
    - Markdown: integration/markdown.md
    - Importing: integration/importing.md
    - Exporting: integration/exporting.md
    - Flat Files: integration/flat-files.md
    - RDF: integration/rdf.md
    - LPG: integration/lpg.md
    - Formal Ontologies: integration/formal-ontologies.md
    - NLP: integration/nlp.md
    - Autocomplete: integration/autocomplete.md
  Glossary: glossary.md
  References: references.md
site_description: 'A book on Personal Knowledge Graphs.  All content licensed Creative Commons ShareAlike Attribution Noncommercial'
site_author: 'Dan McCreary'
repo_name: 'GitHub Repo'
repo_url: 'https://github.com/dmccreary/personal-knowledge-graphs'

# CoderDojo Standards from here down
edit_uri: 'blob/master/docs'
theme:
  # should be name: material
  name: material
  logo: img/coderdojo-logo.png
  palette:
    primary: '#642580'
    accent: '#41BAC1'
  custom_dir: 'theme'
  include_sidebar: true
plugins:
  - search
markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.highlight:
      linenums: true
  - pymdownx.details
  - pymdownx.superfences
